-- MySQL Script generated by MySQL Workbench
-- Fri Jun 18 06:53:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `email` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`email`));


-- -----------------------------------------------------
-- Table `mydb`.`video_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `url_img` VARCHAR(50) NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`search_query`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`search_query` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(255) NOT NULL,
  `user_email` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_search_query_users1_idx` (`user_email` ASC) VISIBLE,
  UNIQUE INDEX `word_UNIQUE` (`word` ASC) VISIBLE,
  CONSTRAINT `fk_search_query_users1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`search_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`search_details` (
  `search_query_id` INT NOT NULL,
  `video_details_id` INT NOT NULL,
  PRIMARY KEY (`search_query_id`, `video_details_id`),
  INDEX `fk_search_query_has_video_details_video_details1_idx` (`video_details_id` ASC) VISIBLE,
  INDEX `fk_search_query_has_video_details_search_query_idx` (`search_query_id` ASC) VISIBLE,
  CONSTRAINT `fk_search_query_has_video_details_search_query`
    FOREIGN KEY (`search_query_id`)
    REFERENCES `mydb`.`search_query` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_search_query_has_video_details_video_details1`
    FOREIGN KEY (`video_details_id`)
    REFERENCES `mydb`.`video_details` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`featured`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`featured` (
  `video_details_id` INT NOT NULL,
  `users_email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`video_details_id`, `users_email`),
  INDEX `fk_video_details_has_users_users1_idx` (`users_email` ASC) VISIBLE,
  INDEX `fk_video_details_has_users_video_details1_idx` (`video_details_id` ASC) VISIBLE,
  CONSTRAINT `fk_video_details_has_users_video_details1`
    FOREIGN KEY (`video_details_id`)
    REFERENCES `mydb`.`video_details` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_details_has_users_users1`
    FOREIGN KEY (`users_email`)
    REFERENCES `mydb`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
